name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Setup"

      - run: echo ${{ github.event.pull_request.head }}

      - run: ${{ tojson(github) }}
        shell: cat {0}
