name: Reporter

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
      - requested

jobs:
  reporter:
    name: Reporter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Reporter"

      - run: ${{ tojson(github) }}
        shell: cat {0}

      # Emulate dorny/paths-filter
      - run: /usr/bin/git fetch --no-tags --depth=100 origin master ${{ github.event.workflow_run.head_sha }}
