name: Reporter

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested
      - completed

jobs:
  reporter:
    name: Reporter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Reporter"
