name: Reporter Alt

on:
  workflow_run:
    workflows: ['CI']
    branches: ['**']
    types:
      - completed
      - requested

jobs:
  reporter-alt:
    name: Reporter Alt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Reporter"
