name: Reporter

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
      - requested

jobs:
  filter_jobs:
    name: Filter jobs
    runs-on: ubuntu-latest
    outputs:
      jsChanged: ${{ steps.filter.outputs.jsChanged }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          # Should be kept in sync with the filter in the CI workflow
          filters: |
            jsChanged: '**/src/**/*.js'

  reporter:
    name: Reporter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Reporter"

      - run: ${{ tojson(github) }}
        shell: cat {0}
